name: ARCHE Ingest Binaries

on:
  workflow_dispatch


jobs:
  build_pages_and_ingest:
    name: ARCHE Ingest
    runs-on: ubuntu-latest
    steps:
    - name: get data
      run: |
        echo "do something to get your data"
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: install python packages
      run: |
        pip install acdh-tei-pyutils
    - name: Fetch Data
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        ./fetch_data.sh
    - name: Copy XML Files to to_ingest 
      run: |
        mkdir $PWD/to_ingest
        find -path "./data/editions/*.xml" -exec cp -prv '{}' './to_ingest' ';'
    - name: List Files
      run: |
        ls ./to_ingest
    - name: install repo-file-checker
      run: |
        composer require "acdh-oeaw/repo-file-checker:^2"
        mkdir -p filechecker/tmp filechecker/reports
    - name: run repo-file-checker
      run: |
        php -f vendor/acdh-oeaw/repo-file-checker/index.php -- --tmpDir filechecker/tmp --reportDir filechecker/reports to_ingest 0
    - name: ingestion dependencies
      run: |
        composer require "acdh-oeaw/arche-ingest:^1"
    - name: ingest binaries
      run: |
        vendor/bin/arche-import-binary to_ingest https://id.acdh.oeaw.ac.at/legalkraus https://arche-dev.acdh-dev.oeaw.ac.at/api ${{secrets.ARCHE_LOGIN}} ${{secrets.ARCHE_PASSWORD}}
